### PR TITLE
Fix/packing controller check quality

### LINKED ISSUE #248: Packing Controller Needs to Check Quantity
Before creating a pack the controller needs to check that all items selected for the pack have sufficient quantities. 

screen shot 2017-09-26 at 7 59 27 pm

### PR DESCRIPTION
**Pull request by ik226**
client/modules/food/components/inventory/FoodItems.js:125 ~138

When `this.state.hasBeenChanged` stays `false` (default), 
this line 
```javascript
(this.state.modalInputFields.quantity !== "" && this.state.modalInputFields.quantity >= 0) || !this.state.hasBeenChanged  ? null : 'error'
```
 allows user to put any quantity value, including negative values. Also, I believe that `this.state.hasBeenChanged` will only become `true` when user changes food name. 

Thus, the approach is to remove parts that checking `this.state.hasBeenChanged`. Instead, we can 
store initial values (name, category, quantity) for each food item when an edit-modal appears. Then, we can decide to disable update button based on comparison between initial values and new inputs.

closes #248

### CODE REVIEW

File: client/modules/food/components/inventory/FoodItems.js [hunk 1]
```diff
@@ -20,7 +20,10 @@ class FoodItems extends React.Component {
       modalInputFields: { name: "", categoryId: "", quantity: "" },
       validInput: false,
       searchText: "",
-      hasBeenChanged: false
+      hasBeenChanged: false,
```
Comment (jspaine) [inline client/modules/food/components/inventory/FoodItems.js]: It doesn't look like this is still used after this change

File: client/modules/food/components/inventory/FoodItems.js [hunk 2]
```diff
@@ -49,6 +52,11 @@ class FoodItems extends React.Component {
       this.setState({
         showModal: 'Edit',
         editModalFood: food,
+        initialModalInputFields: {
```
Comment (jspaine) [inline client/modules/food/components/inventory/FoodItems.js]: Could just define a variable for setting modalInputFields and initialModalInputFields so you don't have to write it twice

File: client/modules/food/components/inventory/FoodItems.js [hunk 3]
```diff
@@ -145,6 +154,14 @@ class FoodItems extends React.Component {
   }
 
   /**
+   *  check whether newly edited values are different from the inital values
+   */
+   checkChanged = () => {
+     //console.log(JSON.stringify(this.state.initialModalInputFields), JSON.stringify(this.state.modalInputFields))
```
Comment (jspaine) [inline client/modules/food/components/inventory/FoodItems.js]: Remeber to remove

File: client/modules/food/components/inventory/FoodItems.js [hunk 4]
```diff
@@ -145,6 +154,14 @@ class FoodItems extends React.Component {
...
+     return JSON.stringify(this.state.initialModalInputFields) === JSON.stringify(this.state.modalInputFields) ? false : true
```
Comment (jspaine) [inline client/modules/food/components/inventory/FoodItems.js]: Rather check explicitly, something like
```js
mapKeys(    // from lodash
  this.state.modalInputFields, 
  (value, key) => value !== this.state.initialModalInputFields[key]
).reduce((acc, x) => acc || x, false)
```

File: client/modules/food/components/inventory/FoodItems.js (hunk 2 above)
Comment (ik226) [reply client/modules/food/components/inventory/FoodItems.js]: can you please elaborate this part further?

Comment (jspaine) [reply client/modules/food/components/inventory/FoodItems.js]: just like this, so if you add/remove a field you don't have to change it in two places:
```js
const inputFields = {...}
this.setState({
   ...
   initialModalInputFields: inputFields,
   modalInputFields: inputFields
})
```

Comment (ik226) [reply client/modules/food/components/inventory/FoodItems.js]: I see! Thanks so much!

**Comment by jspaine** [comment]
Thanks
